version: '3.8'

services:
  mediamtx:
    image: bluenviron/mediamtx:latest-ffmpeg
    environment:
      - MTX_PROTOCOLS=tcp
      - MTX_WEBRTCADDITIONALHOSTS=localhost
      - MTX_WEBRTCLOCALTCPADDRESS=:8189
      # Ensure the correct format for ICE servers configuration
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
      - ./data:/data
    ports:
      - "8554:8554"
      - "8888:8888"
      - "8889:8889"
      - "8890:8890/udp"
      - "8189:8189/udp"
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - hls_stream

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - mediamtx
    networks:
      - hls_stream

  signaling-server:
    build: ./signaling-server
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks: # Corrected to networks (plural) with correct indentation
      - hls_stream

networks:
  hls_stream:
